spring:
  cloud:
    gateway:
      # 网关全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
      routes:
        - id: project-user-aggregation
          uri: lb://project-aggregation/api/user/**
          predicates:
            - Path=/api/user/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/user/code
                  - /api/user/has-email
                  - /api/user/has-username
                  - /api/user/register
                  - /api/user/loginByCode
                  - /api/user/login
                  - /api/user/forget-password
                  - /api/user/loginByOAuth

        - id: project-common-aggregation
          uri: lb://project-aggregation/api/common/**
          predicates:
            - Path=/api/common/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/common/ping
                  - /api/common/files/**

        - id: project-analyze-aggregation
          uri: lb://project-aggregation/api/analyze/**
          predicates:
            - Path=/api/analyze/**
          filters:
            - name: TokenValidate
              args:
                whitePathList:
                  - /api/analyze/ping

project:
  nacos:
    host: 127.0.0.1
    port: 8848
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1