export const ISOTranslation: Record<string, {zh: string, en: string}> = {
    AF: { zh: '阿富汗', en: 'Afghanistan' },
    AL: { zh: '阿尔巴尼亚', en: 'Albania' },
    DZ: { zh: '阿尔及利亚', en: 'Algeria' },
    AO: { zh: '安哥拉', en: 'Angola' },
    AR: { zh: '阿根廷', en: 'Argentina' },
    AM: { zh: '亚美尼亚', en: 'Armenia' },
    AU: { zh: '澳大利亚', en: 'Australia' },
    AT: { zh: '奥地利', en: 'Austria' },
    AZ: { zh: '阿塞拜疆', en: 'Azerbaijan' },
    BH: { zh: '巴林', en: 'Bahrain' },
    BD: { zh: '孟加拉国', en: 'Bangladesh' },
    BY: { zh: '白俄罗斯', en: 'Belarus' },
    BE: { zh: '比利时', en: 'Belgium' },
    BZ: { zh: '伯利兹', en: 'Belize' },
    BJ: { zh: '贝宁', en: 'Benin' },
    BT: { zh: '不丹', en: 'Bhutan' },
    BO: { zh: '玻利维亚', en: 'Bolivia' },
    BA: { zh: '波斯尼亚和黑塞哥维那', en: 'Bosnia and Herzegovina' },
    BW: { zh: '博茨瓦纳', en: 'Botswana' },
    BR: { zh: '巴西', en: 'Brazil' },
    VG: { zh: '英属维京群岛', en: 'British Virgin Islands' },
    BN: { zh: '文莱', en: 'Brunei' },
    BG: { zh: '保加利亚', en: 'Bulgaria' },
    BF: { zh: '布基纳法索', en: 'Burkina Faso' },
    BI: { zh: '布隆迪', en: 'Burundi' },
    KH: { zh: '柬埔寨', en: 'Cambodia' },
    CM: { zh: '喀麦隆', en: 'Cameroon' },
    CA: { zh: '加拿大', en: 'Canada' },
    CV: { zh: '佛得角', en: 'Cape Verde' },
    KY: { zh: '开曼群岛', en: 'Cayman Islands' },
    CF: { zh: '中非共和国', en: 'Central African Republic' },
    TD: { zh: '乍得', en: 'Chad' },
    CL: { zh: '智利', en: 'Chile' },
    CN: { zh: '中国', en: 'China' },
    CO: { zh: '哥伦比亚', en: 'Colombia' },
    KM: { zh: '科摩罗', en: 'Comoros' },
    CG: { zh: '刚果(布)', en: 'Congo - Brazzaville' },
    CD: { zh: '刚果(金)', en: 'Congo - Kinshasa' },
    CR: { zh: '哥斯达黎加', en: 'Costa Rica' },
    HR: { zh: '克罗地亚', en: 'Croatia' },
    CY: { zh: '塞浦路斯', en: 'Cyprus' },
    CZ: { zh: '捷克共和国', en: 'Czech Republic' },
    DK: { zh: '丹麦', en: 'Denmark' },
    DJ: { zh: '吉布提', en: 'Djibouti' },
    DO: { zh: '多米尼加共和国', en: 'Dominican Republic' },
    EC: { zh: '厄瓜多尔', en: 'Ecuador' },
    EG: { zh: '埃及', en: 'Egypt' },
    SV: { zh: '萨尔瓦多', en: 'EI Salvador' },
    GQ: { zh: '赤道几内亚', en: 'Equatorial Guinea' },
    ER: { zh: '厄立特里亚', en: 'Eritrea' },
    EE: { zh: '爱沙尼亚', en: 'Estonia' },
    ET: { zh: '埃塞俄比亚', en: 'Ethiopia' },
    FJ: { zh: '斐济', en: 'Fiji' },
    FI: { zh: '芬兰', en: 'Finland' },
    FR: { zh: '法国', en: 'France' },
    GA: { zh: '加蓬', en: 'Gabon' },
    GM: { zh: '冈比亚', en: 'Gambia' },
    GE: { zh: '格鲁吉亚', en: 'Georgia' },
    DE: { zh: '德国', en: 'Germany' },
    GH: { zh: '加纳', en: 'Ghana' },
    GR: { zh: '希腊', en: 'Greece' },
    GL: { zh: '格陵兰', en: 'Greenland' },
    GT: { zh: '危地马拉', en: 'Guatemala' },
    GN: { zh: '几内亚', en: 'Guinea' },
    GY: { zh: '圭亚那', en: 'Guyana' },
    HT: { zh: '海地', en: 'Haiti' },
    HN: { zh: '洪都拉斯', en: 'Honduras' },
    HK: { zh: '中国香港特别行政区', en: 'Hongkong SAR China' },
    HU: { zh: '匈牙利', en: 'Hungary' },
    IS: { zh: '冰岛', en: 'Iceland' },
    IN: { zh: '印度', en: 'India' },
    ID: { zh: '印度尼西亚', en: 'Indonesia' },
    IR: { zh: '伊朗', en: 'Iran' },
    IQ: { zh: '伊拉克', en: 'Iraq' },
    IE: { zh: '爱尔兰', en: 'Ireland' },
    IM: { zh: '马恩岛', en: 'Isle of Man' },
    IL: { zh: '以色列', en: 'Israel' },
    IT: { zh: '意大利', en: 'Italy' },
    CI: { zh: '科特迪瓦', en: 'Ivory Coast' },
    JM: { zh: '牙买加', en: 'Jamaica' },
    JP: { zh: '日本', en: 'Japan' },
    JO: { zh: '约旦', en: 'Jordan' },
    KZ: { zh: '哈萨克斯坦', en: 'Kazakhstan' },
    KE: { zh: '肯尼亚', en: 'Kenya' },
    KR: { zh: '韩国', en: 'Korea' },
    KW: { zh: '科威特', en: 'Kuwait' },
    KG: { zh: '吉尔吉斯斯坦', en: 'Kyrgyzstan' },
    LA: { zh: '老挝', en: 'Laos' },
    LV: { zh: '拉脱维亚', en: 'Latvia' },
    LB: { zh: '黎巴嫩', en: 'Lebanon' },
    LS: { zh: '莱索托', en: 'Lesotho' },
    LR: { zh: '利比里亚', en: 'Liberia' },
    LY: { zh: '利比亚', en: 'Libya' },
    LT: { zh: '立陶宛', en: 'Lithuania' },
    LU: { zh: '卢森堡', en: 'Luxembourg' },
    MO: { zh: '中国澳门特别行政区', en: 'Macao SAR China' },
    MK: { zh: '马其顿', en: 'Macedonia' },
    MG: { zh: '马达加斯加', en: 'Madagascar' },
    MW: { zh: '马拉维', en: 'Malawi' },
    MY: { zh: '马来西亚', en: 'Malaysia' },
    MV: { zh: '马尔代夫', en: 'Maldives' },
    ML: { zh: '马里', en: 'Mali' },
    MT: { zh: '马耳他', en: 'Malta' },
    MR: { zh: '毛利塔尼亚', en: 'Mauritania' },
    MU: { zh: '毛里求斯', en: 'Mauritius' },
    MX: { zh: '墨西哥', en: 'Mexico' },
    MD: { zh: '摩尔多瓦', en: 'Moldova' },
    MC: { zh: '摩纳哥', en: 'Monaco' },
    MN: { zh: '蒙古', en: 'Mongolia' },
    ME: { zh: '黑山共和国', en: 'Montenegro' },
    MA: { zh: '摩洛哥', en: 'Morocco' },
    MZ: { zh: '莫桑比克', en: 'Mozambique' },
    MM: { zh: '缅甸', en: 'Myanmar(Burma)' },
    NA: { zh: '纳米比亚', en: 'Namibia' },
    NP: { zh: '尼泊尔', en: 'Nepal' },
    NL: { zh: '荷兰', en: 'Netherlands' },
    NZ: { zh: '新西兰', en: 'New Zealand' },
    NI: { zh: '尼加拉瓜', en: 'Nicaragua' },
    NE: { zh: '尼日尔', en: 'Niger' },
    NG: { zh: '尼日利亚', en: 'Nigeria' },
    KP: { zh: '朝鲜', en: 'North Korea' },
    NO: { zh: '挪威', en: 'Norway' },
    OM: { zh: '阿曼', en: 'Oman' },
    PK: { zh: '巴基斯坦', en: 'Pakistan' },
    PA: { zh: '巴拿马', en: 'Panama' },
    PY: { zh: '巴拉圭', en: 'Paraguay' },
    PE: { zh: '秘鲁', en: 'Peru' },
    PH: { zh: '菲律宾', en: 'Philippines' },
    PL: { zh: '波兰', en: 'Poland' },
    PT: { zh: '葡萄牙', en: 'Portugal' },
    PR: { zh: '波多黎各', en: 'Puerto Rico' },
    QA: { zh: '卡塔尔', en: 'Qatar' },
    RE: { zh: '留尼旺', en: 'Reunion' },
    RO: { zh: '罗马尼亚', en: 'Romania' },
    RU: { zh: '俄罗斯', en: 'Russia' },
    RW: { zh: '卢旺达', en: 'Rwanda' },
    SM: { zh: '圣马力诺', en: 'San Marino' },
    SA: { zh: '沙特阿拉伯', en: 'Saudi Arabia' },
    SN: { zh: '塞内加尔', en: 'Senegal' },
    RS: { zh: '塞尔维亚', en: 'Serbia' },
    SL: { zh: '塞拉利昂', en: 'Sierra Leone' },
    SG: { zh: '新加坡', en: 'Singapore' },
    SK: { zh: '斯洛伐克', en: 'Slovakia' },
    SI: { zh: '斯洛文尼亚', en: 'Slovenia' },
    SO: { zh: '索马里', en: 'Somalia' },
    ZA: { zh: '南非', en: 'South Africa' },
    ES: { zh: '西班牙', en: 'Spain' },
    LK: { zh: '斯里兰卡', en: 'Sri Lanka' },
    SD: { zh: '苏丹', en: 'Sudan' },
    SR: { zh: '苏里南', en: 'Suriname' },
    SZ: { zh: '斯威士兰', en: 'Swaziland' },
    SE: { zh: '瑞典', en: 'Sweden' },
    CH: { zh: '瑞士', en: 'Switzerland' },
    SY: { zh: '叙利亚', en: 'Syria' },
    TW: { zh: '中国台湾', en: 'Taiwan' },
    TJ: { zh: '塔吉克斯坦', en: 'Tajikistan' },
    TZ: { zh: '坦桑尼亚', en: 'Tanzania' },
    TH: { zh: '泰国', en: 'Thailand' },
    TG: { zh: '多哥', en: 'Togo' },
    TO: { zh: '汤加', en: 'Tonga' },
    TT: { zh: '特立尼达和多巴哥', en: 'Trinidad and Tobago' },
    TN: { zh: '突尼斯', en: 'Tunisia' },
    TR: { zh: '土耳其', en: 'Turkey' },
    TM: { zh: '土库曼斯坦', en: 'Turkmenistan' },
    VI: { zh: '美属维尔京群岛', en: 'U.S. Virgin Islands' },
    UG: { zh: '乌干达', en: 'Uganda' },
    UA: { zh: '乌克兰', en: 'Ukraine' },
    AE: { zh: '阿拉伯联合酋长国', en: 'United Arab Emirates' },
    GB: { zh: '英国', en: 'United Kingdom' },
    US: { zh: '美国', en: 'USA' },
    UY: { zh: '乌拉圭', en: 'Uruguay' },
    UZ: { zh: '乌兹别克斯坦', en: 'Uzbekistan' },
    VA: { zh: '梵蒂冈城', en: 'Vatican City' },
    VE: { zh: '委内瑞拉', en: 'Venezuela' },
    VN: { zh: '越南', en: 'Vietnam' },
    YE: { zh: '也门', en: 'Yemen' },
    YU: { zh: '南斯拉夫', en: 'Yugoslavia' },
    ZR: { zh: '扎伊尔', en: 'Zaire' },
    ZM: { zh: '赞比亚', en: 'Zambia' },
    ZW: { zh: '津巴布韦', en: 'Zimbabwe' }
}

export const translateISOToLocale = (iso: string, locale: string) => {
    return ISOTranslation[iso][locale as "zh" | "en"];
}