project:
  nacos:
    host: 127.0.0.1
    port: 8848
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  rocketmq:
    name-server: 127.0.0.1:9876
    producer:
      group: common-message-execute_pg
  ai:
    apiKey: your-api-key