server:
  port: 9015

spring:
  profiles:
    active: prod
  application:
    name: project-analyze
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${spring.profiles.active}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${project.nacos.host}:${project.nacos.port}
  data:
    redis:
      host: ${project.redis.host}
      port: ${project.redis.port}
    # password: ${project.redis.password}
      database: ${project.redis.database}

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: ${project.rocketmq.name-server}
  producer:
    group: ${project.rocketmq.producer.group}
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

ai:
  apiKey: ${project.ai.apiKey}