/** 这个文件来放点示例用的 */

export const userEX = {
    login: 'Heuluck',
    id: 89375068,
    user_view_type: 'public',
    node_id: 'MDQ6VXNlcjg5Mzc1MDY4',
    avatar_url: 'https://avatars.githubusercontent.com/u/89375068?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Heuluck',
    html_url: 'https://github.com/Heuluck',
    followers_url: 'https://api.github.com/users/Heuluck/followers',
    following_url: 'https://api.github.com/users/Heuluck/following{/other_user}',
    gists_url: 'https://api.github.com/users/Heuluck/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Heuluck/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Heuluck/subscriptions',
    organizations_url: 'https://api.github.com/users/Heuluck/orgs',
    repos_url: 'https://api.github.com/users/Heuluck/repos',
    events_url: 'https://api.github.com/users/Heuluck/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Heuluck/received_events',
    type: 'User',
    site_admin: false,
    name: 'Heuluck Lu',
    company: '@NCUHOME',
    blog: 'https://heuluck.top',
    location: null,
    email: null,
    hireable: null,
    bio: 'Furry / Frontend / Full-Stack Dev / NCUHOMER',
    twitter_username: null,
    public_repos: 11,
    public_gists: 0,
    followers: 12,
    following: 26,
    created_at: '2021-08-23T05:43:15Z',
    updated_at: '2024-10-25T04:56:56Z',
};

export const userPRsEX = {
    total_count: 4,
    incomplete_results: false,
    items: [
        {
            url: 'https://api.github.com/repos/Heuluck/luck-blog/issues/1',
            repository_url: 'https://api.github.com/repos/Heuluck/luck-blog',
            labels_url: 'https://api.github.com/repos/Heuluck/luck-blog/issues/1/labels{/name}',
            comments_url: 'https://api.github.com/repos/Heuluck/luck-blog/issues/1/comments',
            events_url: 'https://api.github.com/repos/Heuluck/luck-blog/issues/1/events',
            html_url: 'https://github.com/Heuluck/luck-blog/pull/1',
            id: 2333995902,
            node_id: 'PR_kwDOMEvMyc5xc8fM',
            number: 1,
            title: 'feat: 完成文章页面、后端api以及主页到文章的跳转',
            user: {
                login: 'Heuluck',
                id: 89375068,
                node_id: 'MDQ6VXNlcjg5Mzc1MDY4',
                avatar_url: 'https://avatars.githubusercontent.com/u/89375068?v=4',
                gravatar_id: '',
                url: 'https://api.github.com/users/Heuluck',
                html_url: 'https://github.com/Heuluck',
                followers_url: 'https://api.github.com/users/Heuluck/followers',
                following_url: 'https://api.github.com/users/Heuluck/following{/other_user}',
                gists_url: 'https://api.github.com/users/Heuluck/gists{/gist_id}',
                starred_url: 'https://api.github.com/users/Heuluck/starred{/owner}{/repo}',
                subscriptions_url: 'https://api.github.com/users/Heuluck/subscriptions',
                organizations_url: 'https://api.github.com/users/Heuluck/orgs',
                repos_url: 'https://api.github.com/users/Heuluck/repos',
                events_url: 'https://api.github.com/users/Heuluck/events{/privacy}',
                received_events_url: 'https://api.github.com/users/Heuluck/received_events',
                type: 'User',
                user_view_type: 'public',
                site_admin: false,
            },
            labels: [],
            state: 'closed',
            locked: true,
            assignee: null,
            assignees: [],
            milestone: null,
            comments: 0,
            created_at: '2024-06-04T17:06:11Z',
            updated_at: '2024-06-04T17:07:22Z',
            closed_at: '2024-06-04T17:07:22Z',
            author_association: 'OWNER',
            active_lock_reason: null,
            draft: false,
            pull_request: {
                url: 'https://api.github.com/repos/Heuluck/luck-blog/pulls/1',
                html_url: 'https://github.com/Heuluck/luck-blog/pull/1',
                diff_url: 'https://github.com/Heuluck/luck-blog/pull/1.diff',
                patch_url: 'https://github.com/Heuluck/luck-blog/pull/1.patch',
                merged_at: '2024-06-04T17:07:22Z',
            },
            body: null,
            reactions: {
                url: 'https://api.github.com/repos/Heuluck/luck-blog/issues/1/reactions',
                total_count: 0,
                '+1': 0,
                '-1': 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            timeline_url: 'https://api.github.com/repos/Heuluck/luck-blog/issues/1/timeline',
            performed_via_github_app: null,
            state_reason: null,
            score: 1,
        },
        {
            url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/3',
            repository_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake',
            labels_url:
                'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/3/labels{/name}',
            comments_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/3/comments',
            events_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/3/events',
            html_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/3',
            id: 2060726490,
            node_id: 'PR_kwDOK-Nxbc5i98XI',
            number: 3,
            title: 'feat:中英文切换和一键复制',
            user: {
                login: 'Heuluck',
                id: 89375068,
                node_id: 'MDQ6VXNlcjg5Mzc1MDY4',
                avatar_url: 'https://avatars.githubusercontent.com/u/89375068?v=4',
                gravatar_id: '',
                url: 'https://api.github.com/users/Heuluck',
                html_url: 'https://github.com/Heuluck',
                followers_url: 'https://api.github.com/users/Heuluck/followers',
                following_url: 'https://api.github.com/users/Heuluck/following{/other_user}',
                gists_url: 'https://api.github.com/users/Heuluck/gists{/gist_id}',
                starred_url: 'https://api.github.com/users/Heuluck/starred{/owner}{/repo}',
                subscriptions_url: 'https://api.github.com/users/Heuluck/subscriptions',
                organizations_url: 'https://api.github.com/users/Heuluck/orgs',
                repos_url: 'https://api.github.com/users/Heuluck/repos',
                events_url: 'https://api.github.com/users/Heuluck/events{/privacy}',
                received_events_url: 'https://api.github.com/users/Heuluck/received_events',
                type: 'User',
                user_view_type: 'public',
                site_admin: false,
            },
            labels: [],
            state: 'closed',
            locked: false,
            assignee: null,
            assignees: [],
            milestone: null,
            comments: 0,
            created_at: '2023-12-30T11:58:07Z',
            updated_at: '2023-12-30T11:58:58Z',
            closed_at: '2023-12-30T11:58:58Z',
            author_association: 'OWNER',
            active_lock_reason: null,
            draft: false,
            pull_request: {
                url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pulls/3',
                html_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/3',
                diff_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/3.diff',
                patch_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/3.patch',
                merged_at: '2023-12-30T11:58:58Z',
            },
            body: null,
            reactions: {
                url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/3/reactions',
                total_count: 0,
                '+1': 0,
                '-1': 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            timeline_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/3/timeline',
            performed_via_github_app: null,
            state_reason: null,
            score: 1,
        },
        {
            url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/2',
            repository_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake',
            labels_url:
                'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/2/labels{/name}',
            comments_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/2/comments',
            events_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/2/events',
            html_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/2',
            id: 2060286365,
            node_id: 'PR_kwDOK-Nxbc5i8oPm',
            number: 2,
            title: 'feat:全新的修改已有项功能',
            user: {
                login: 'Heuluck',
                id: 89375068,
                node_id: 'MDQ6VXNlcjg5Mzc1MDY4',
                avatar_url: 'https://avatars.githubusercontent.com/u/89375068?v=4',
                gravatar_id: '',
                url: 'https://api.github.com/users/Heuluck',
                html_url: 'https://github.com/Heuluck',
                followers_url: 'https://api.github.com/users/Heuluck/followers',
                following_url: 'https://api.github.com/users/Heuluck/following{/other_user}',
                gists_url: 'https://api.github.com/users/Heuluck/gists{/gist_id}',
                starred_url: 'https://api.github.com/users/Heuluck/starred{/owner}{/repo}',
                subscriptions_url: 'https://api.github.com/users/Heuluck/subscriptions',
                organizations_url: 'https://api.github.com/users/Heuluck/orgs',
                repos_url: 'https://api.github.com/users/Heuluck/repos',
                events_url: 'https://api.github.com/users/Heuluck/events{/privacy}',
                received_events_url: 'https://api.github.com/users/Heuluck/received_events',
                type: 'User',
                user_view_type: 'public',
                site_admin: false,
            },
            labels: [],
            state: 'closed',
            locked: false,
            assignee: null,
            assignees: [],
            milestone: null,
            comments: 0,
            created_at: '2023-12-29T17:42:33Z',
            updated_at: '2023-12-29T17:43:35Z',
            closed_at: '2023-12-29T17:43:35Z',
            author_association: 'OWNER',
            active_lock_reason: null,
            draft: false,
            pull_request: {
                url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pulls/2',
                html_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/2',
                diff_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/2.diff',
                patch_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/2.patch',
                merged_at: '2023-12-29T17:43:35Z',
            },
            body: null,
            reactions: {
                url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/2/reactions',
                total_count: 0,
                '+1': 0,
                '-1': 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            timeline_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/2/timeline',
            performed_via_github_app: null,
            state_reason: null,
            score: 1,
        },
        {
            url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/1',
            repository_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake',
            labels_url:
                'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/1/labels{/name}',
            comments_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/1/comments',
            events_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/1/events',
            html_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/1',
            id: 2059080346,
            node_id: 'PR_kwDOK-Nxbc5i6zFu',
            number: 1,
            title: 'feat: 完成列表以及删除功能',
            user: {
                login: 'Heuluck',
                id: 89375068,
                node_id: 'MDQ6VXNlcjg5Mzc1MDY4',
                avatar_url: 'https://avatars.githubusercontent.com/u/89375068?v=4',
                gravatar_id: '',
                url: 'https://api.github.com/users/Heuluck',
                html_url: 'https://github.com/Heuluck',
                followers_url: 'https://api.github.com/users/Heuluck/followers',
                following_url: 'https://api.github.com/users/Heuluck/following{/other_user}',
                gists_url: 'https://api.github.com/users/Heuluck/gists{/gist_id}',
                starred_url: 'https://api.github.com/users/Heuluck/starred{/owner}{/repo}',
                subscriptions_url: 'https://api.github.com/users/Heuluck/subscriptions',
                organizations_url: 'https://api.github.com/users/Heuluck/orgs',
                repos_url: 'https://api.github.com/users/Heuluck/repos',
                events_url: 'https://api.github.com/users/Heuluck/events{/privacy}',
                received_events_url: 'https://api.github.com/users/Heuluck/received_events',
                type: 'User',
                user_view_type: 'public',
                site_admin: false,
            },
            labels: [],
            state: 'closed',
            locked: false,
            assignee: null,
            assignees: [],
            milestone: null,
            comments: 0,
            created_at: '2023-12-29T05:27:18Z',
            updated_at: '2023-12-29T07:50:17Z',
            closed_at: '2023-12-29T05:27:51Z',
            author_association: 'OWNER',
            active_lock_reason: null,
            draft: false,
            pull_request: {
                url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pulls/1',
                html_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/1',
                diff_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/1.diff',
                patch_url: 'https://github.com/Heuluck/Create-infoboxes-in-Mediawiki-Remake/pull/1.patch',
                merged_at: '2023-12-29T05:27:51Z',
            },
            body: '一般来说没什么bug',
            reactions: {
                url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/1/reactions',
                total_count: 0,
                '+1': 0,
                '-1': 0,
                laugh: 0,
                hooray: 0,
                confused: 0,
                heart: 0,
                rocket: 0,
                eyes: 0,
            },
            timeline_url: 'https://api.github.com/repos/Heuluck/Create-infoboxes-in-Mediawiki-Remake/issues/1/timeline',
            performed_via_github_app: null,
            state_reason: null,
            score: 1,
        },
    ],
};
